import { Header } from '@/stories'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Header onCreateAccount={()=> {}} onLogin={()=> {}} onLogout={() => {}}/>
      {children}
    </>
  )
}
